version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - ${UI_SERVICE_PORT}:${UI_SERVICE_PORT}/tcp
    networks:
      - front_net
  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  front_net:
    driver: bridge
  back_net:
    driver: bridge
