version: '3'
services:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - back_net
      - front_net

  fluentd:
    image: ${USER_NAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"


  elasticsearch:
    image: elasticsearch:7.3.2
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"


  kibana:
    image: kibana:7.3.2
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"

networks:
  front_net:
    driver: bridge
  back_net:
    driver: bridge
